# Generated by Django 4.2.3 on 2023-07-23 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Genre',
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('rated', models.CharField(max_length=20)),
                ('released', models.DateField()),
                ('runtime', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=255)),
                ('writer', models.CharField(max_length=255)),
                ('actors', models.TextField()),
                ('plot', models.TextField()),
                ('language', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('awards', models.TextField()),
                ('poster', models.URLField()),
                ('meta_score', models.PositiveIntegerField()),
                ('imdb_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('imdb_votes', models.PositiveIntegerField()),
                ('imdb_id', models.CharField(max_length=20)),
                ('movie_type', models.CharField(max_length=50)),
                ('dvd', models.DateField()),
                ('box_office', models.CharField(max_length=100)),
                ('production', models.CharField(max_length=255)),
                ('website', models.URLField()),
            ],
            options={
                'db_table': 'Movies',
            },
        ),
        migrations.CreateModel(
            name='RatingProvider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'RatingProvider',
            },
        ),
        migrations.CreateModel(
            name='MovieRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=1, max_digits=3)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movies')),
                ('rating_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.ratingprovider')),
            ],
            options={
                'db_table': 'MovieRating',
            },
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.genre')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movies')),
            ],
            options={
                'db_table': 'MovieGenre',
            },
        ),
    ]
