# Generated by Django 4.2.3 on 2023-07-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_movie_type_movies_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierating',
            name='value',
            field=models.CharField(max_length=20),
        ),
    ]
