# Generated by Django 4.2.3 on 2023-07-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movies_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='website',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
