# Generated by Django 4.2.3 on 2023-07-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movies_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='dvd',
            field=models.DateField(default=None, null=True),
        ),
    ]
